# -*- coding: utf-8 -*-
"""Fraud_main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIycK-lWsQa4kN0BAtnuqgkyxSFhpueA
"""

import pandas as pd
import numpy as np
from joblib import dump
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("Fraud_Analysis_Dataset.csv")

#droping the irrelevent feature
df.drop(columns=['nameOrig','nameDest'], inplace=True)

label_encoder = LabelEncoder()
df_encoded = df.copy()
df_encoded['type'] = label_encoder.fit_transform(df_encoded['type'])

x = df_encoded.drop('isFraud', axis=1)
y = df_encoded['isFraud']

# Splitting data into train and test sets
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

# Define the base Random Forest model
RF = RandomForestClassifier(class_weight = 'balanced')
RF.fit(xtrain, ytrain)

# saving the model in a file
dump(RF, 'RF_Model.joblib')