# -*- coding: utf-8 -*-
"""Fraud_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TP8IJsLA2uyQzkBhgXUvPG4jeuis4Uhy
"""

import streamlit as st
import pandas as pd
from joblib import load

model = load('RF_Model.joblib')

st.title('Fraud Detection Prediction App')
st.markdown('Please Enter the Transaction Details and use the predict button')

st.divider()

transaction_type = st.selectbox('Transaction Type', ['CASH_IN', 'CASH_OUT', 'DEBIT', 'PAYMENT', 'TRANSFER'])
time = st.number_input('Time(in hour)', min_value=1, value=1)
amount = st.number_input('Amount', min_value=0.0, value=1000.0)
old_balanceOrg = st.number_input('Old Balance (Sender)', min_value=0.0, value=10000.0)
new_balanceOrg = st.number_input('New Balance (Sender)', min_value=0.0, value=9000.0)
old_balanceDest = st.number_input('Old Balance (Receiver)', min_value=0.0, value=0.0)
new_balanceDest = st.number_input('New Balance (Receiver)', min_value=0.0, value=0.0)

label_mapping = {
    'CASH_IN': 0,
    'CASH_OUT': 1,
    'DEBIT': 2,
    'PAYMENT': 3,
    'TRANSFER': 4
}
transaction_type = label_mapping[transaction_type]

if st.button('Predict'):
  input_data = pd.DataFrame([{
      'step': time,
      'type': transaction_type,
      'amount': amount,
      'oldbalanceOrg': old_balanceOrg,
      'newbalanceOrig': new_balanceOrg,
      'oldbalanceDest': old_balanceDest,
      'newbalanceDest': new_balanceDest
  }])
  prediction = model.predict(input_data)[0]
  st.subheader(f"Prediction: '{int(prediction)}'")
  if prediction == 1:
    st.error('Fraudulent Transaction')
  else:
    st.success('Non-Fraudulent Transaction')